# Generated by Django 3.0.4 on 2020-03-15 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=255, null=True)),
                ('answer', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_shown_at', models.DateTimeField(auto_now_add=True)),
                ('next_due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('difficulty_level', models.FloatField(default=2.5)),
                ('consec_correct_answers', models.IntegerField(default=0)),
            ],
        ),
    ]
