# Generated by Django 3.0.4 on 2020-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='easiness',
            new_name='difficulty_level',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
