# Generated by Django 3.0.4 on 2020-03-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20200312_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='image',
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
